#!/usr/bin/env python
from then.exceptions import catch
from then.management import manage

if __name__ == '__main__':
    catch(manage)()
